### ISSUE TITLE
move all 'non-shared' packages to 'broken' label or deprecated, but not main

### ISSUE THREAD

**Issue by k-dominik** [conda-forge/lemon-feedstock#23]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Currently, installing vigra via `conda create -n tmp python=3.8 vigra -y` will pick an outdated lemon version `conda-forge/linux-64::lemon-1.3.1-1`, which didn't come with share libraries. Hence something like

```Python
>>> import vigra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../envs/tmp/lib/python3.8/site-packages/vigra/__init__.py", line 118, in <module>
    import vigra.analysis as analysis
ImportError: libemon.so.1.3.1: cannot open shared object file: No such file or directory
```
fails.

It works of course, when lemon is forced to the latest version:
```bash
conda create -n tmp4 python=3.8 vigra lemon="1.3.1=he9d42e9_3" -y
```

The old packages were only good for building stuff, really, so imo they can be safely removed from `main`.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
boost                     1.74.0           py38hc10631b_3    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
coincbc                   2.10.5               hcee13e7_1    conda-forge
fftw                      3.3.9           nompi_h74d3f13_101    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
ilmbase                   2.5.5                h780b84a_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_1    conda-forge
lemon                     1.3.1                         1    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.21.0           py38h9894fe3_0    conda-forge
openexr                   2.5.5                hf817b99_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.1.3             pyhd8ed1ab_0    conda-forge
python                    3.8.10          h49503c6_1_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
sqlite                    3.36.0               h9cd32fc_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
vigra                     1.11.1          py38h105465b_1023    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge



```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : tmp
    active env location : /home/.../envs/tmp3
            shell level : 2
       user config file : /home/../.condarc
 populated config files : /home/../.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.6.final.0
       virtual packages : __linux=5.8.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/...  (writable)
      conda av data dir : /home/.../etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/ilastik-forge/linux-64
                          https://conda.anaconda.org/ilastik-forge/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/kutra/miniconda3/pkgs
                          /home/../.conda/pkgs
       envs directories : /home/.../envs
                          /home/../.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.6 Linux/5.8.0-59-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False



```
</details>

**Comment by stuarteberg** [comment]
@k-dominik Thanks for reporting this!  I just ran into the same issue.  I guess someone will have to enumerate the list of broken packages and make a PR to [conda-froge/admin-requests][1] as [described in the conda-forge docs][docs].  I've never done that yet, but I notice [you're already familiar with the procedure][2]. :-)

Do you know exactly which packages need to be flagged?

[1]: https://github.com/conda-forge/admin-requests
[2]: https://github.com/conda-forge/admin-requests/pull/162
[docs]: https://conda-forge.org/docs/maintainer/updating_pkgs.html#maint-fix-broken-packages

**Comment by k-dominik** [comment]
Hey @stuarteberg, right on :) In principle I remember the PR when shared builds were finally introduced, so finding the version numbers should not be hard. I'm not sure if "broken" is the correct label though. I'd prefer to move them to deprecated or something like this. Also I stumbled over [conda-forge/conda-forge-repodata-patches-feedstock](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) where one could introduce a rule for lemon... But I guess I'll throw one at admin-requests and see about the reaction :)

**Comment by k-dominik** [comment]
fixed in https://github.com/conda-forge/admin-requests/pull/275
